// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sf/worker/v1/pool.proto

package pbworkerconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/streamingfast/worker-pool-protocol/pb/sf/worker/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WorkerPoolName is the fully-qualified name of the WorkerPool service.
	WorkerPoolName = "sf.worker.v1.WorkerPool"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WorkerPoolWorkersStateProcedure is the fully-qualified name of the WorkerPool's WorkersState RPC.
	WorkerPoolWorkersStateProcedure = "/sf.worker.v1.WorkerPool/WorkersState"
	// WorkerPoolBorrowWorkerProcedure is the fully-qualified name of the WorkerPool's BorrowWorker RPC.
	WorkerPoolBorrowWorkerProcedure = "/sf.worker.v1.WorkerPool/BorrowWorker"
	// WorkerPoolKeepAliveProcedure is the fully-qualified name of the WorkerPool's KeepAlive RPC.
	WorkerPoolKeepAliveProcedure = "/sf.worker.v1.WorkerPool/KeepAlive"
	// WorkerPoolReturnWorkerProcedure is the fully-qualified name of the WorkerPool's ReturnWorker RPC.
	WorkerPoolReturnWorkerProcedure = "/sf.worker.v1.WorkerPool/ReturnWorker"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	workerPoolServiceDescriptor            = v1.File_sf_worker_v1_pool_proto.Services().ByName("WorkerPool")
	workerPoolWorkersStateMethodDescriptor = workerPoolServiceDescriptor.Methods().ByName("WorkersState")
	workerPoolBorrowWorkerMethodDescriptor = workerPoolServiceDescriptor.Methods().ByName("BorrowWorker")
	workerPoolKeepAliveMethodDescriptor    = workerPoolServiceDescriptor.Methods().ByName("KeepAlive")
	workerPoolReturnWorkerMethodDescriptor = workerPoolServiceDescriptor.Methods().ByName("ReturnWorker")
)

// WorkerPoolClient is a client for the sf.worker.v1.WorkerPool service.
type WorkerPoolClient interface {
	// Return the current worker state for a organization/service pair.
	WorkersState(context.Context, *connect.Request[v1.WorkersStateRequest]) (*connect.Response[v1.WorkersStateResponse], error)
	// Create and register a `worker key` for the organization service that needs to access a service.
	// If there no more worker available for a organization/service pair it should return a response with status `resource_exhausted`.
	// Otherwise it should return a response with `worker key` and a status `borrowed`
	// If the organization has exceeded his resource consumption (other than the pool, ex: bytes, requests, blocks...),
	//
	//	an error will be returned with code ResourceExhausted
	BorrowWorker(context.Context, *connect.Request[v1.BorrowWorkerRequest]) (*connect.Response[v1.BorrowWorkerResponse], error)
	// Extend the ttl a worker key. This is useful if your worker keys a store in a database that support ttl
	// If the organization has exceeded his resource consumption (other than the pool, ex: bytes, requests, blocks...),
	//
	//	an error will be returned with code ResourceExhausted
	KeepAlive(context.Context, *connect.Request[v1.KeepAliveRequest]) (*connect.Response[v1.KeepAliveResponse], error)
	// Returning a worker should increase the number of worker available for a organization/service pair
	ReturnWorker(context.Context, *connect.Request[v1.ReturnWorkerRequest]) (*connect.Response[v1.ReturnWorkerResponse], error)
}

// NewWorkerPoolClient constructs a client for the sf.worker.v1.WorkerPool service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWorkerPoolClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WorkerPoolClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &workerPoolClient{
		workersState: connect.NewClient[v1.WorkersStateRequest, v1.WorkersStateResponse](
			httpClient,
			baseURL+WorkerPoolWorkersStateProcedure,
			connect.WithSchema(workerPoolWorkersStateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		borrowWorker: connect.NewClient[v1.BorrowWorkerRequest, v1.BorrowWorkerResponse](
			httpClient,
			baseURL+WorkerPoolBorrowWorkerProcedure,
			connect.WithSchema(workerPoolBorrowWorkerMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		keepAlive: connect.NewClient[v1.KeepAliveRequest, v1.KeepAliveResponse](
			httpClient,
			baseURL+WorkerPoolKeepAliveProcedure,
			connect.WithSchema(workerPoolKeepAliveMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		returnWorker: connect.NewClient[v1.ReturnWorkerRequest, v1.ReturnWorkerResponse](
			httpClient,
			baseURL+WorkerPoolReturnWorkerProcedure,
			connect.WithSchema(workerPoolReturnWorkerMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// workerPoolClient implements WorkerPoolClient.
type workerPoolClient struct {
	workersState *connect.Client[v1.WorkersStateRequest, v1.WorkersStateResponse]
	borrowWorker *connect.Client[v1.BorrowWorkerRequest, v1.BorrowWorkerResponse]
	keepAlive    *connect.Client[v1.KeepAliveRequest, v1.KeepAliveResponse]
	returnWorker *connect.Client[v1.ReturnWorkerRequest, v1.ReturnWorkerResponse]
}

// WorkersState calls sf.worker.v1.WorkerPool.WorkersState.
func (c *workerPoolClient) WorkersState(ctx context.Context, req *connect.Request[v1.WorkersStateRequest]) (*connect.Response[v1.WorkersStateResponse], error) {
	return c.workersState.CallUnary(ctx, req)
}

// BorrowWorker calls sf.worker.v1.WorkerPool.BorrowWorker.
func (c *workerPoolClient) BorrowWorker(ctx context.Context, req *connect.Request[v1.BorrowWorkerRequest]) (*connect.Response[v1.BorrowWorkerResponse], error) {
	return c.borrowWorker.CallUnary(ctx, req)
}

// KeepAlive calls sf.worker.v1.WorkerPool.KeepAlive.
func (c *workerPoolClient) KeepAlive(ctx context.Context, req *connect.Request[v1.KeepAliveRequest]) (*connect.Response[v1.KeepAliveResponse], error) {
	return c.keepAlive.CallUnary(ctx, req)
}

// ReturnWorker calls sf.worker.v1.WorkerPool.ReturnWorker.
func (c *workerPoolClient) ReturnWorker(ctx context.Context, req *connect.Request[v1.ReturnWorkerRequest]) (*connect.Response[v1.ReturnWorkerResponse], error) {
	return c.returnWorker.CallUnary(ctx, req)
}

// WorkerPoolHandler is an implementation of the sf.worker.v1.WorkerPool service.
type WorkerPoolHandler interface {
	// Return the current worker state for a organization/service pair.
	WorkersState(context.Context, *connect.Request[v1.WorkersStateRequest]) (*connect.Response[v1.WorkersStateResponse], error)
	// Create and register a `worker key` for the organization service that needs to access a service.
	// If there no more worker available for a organization/service pair it should return a response with status `resource_exhausted`.
	// Otherwise it should return a response with `worker key` and a status `borrowed`
	// If the organization has exceeded his resource consumption (other than the pool, ex: bytes, requests, blocks...),
	//
	//	an error will be returned with code ResourceExhausted
	BorrowWorker(context.Context, *connect.Request[v1.BorrowWorkerRequest]) (*connect.Response[v1.BorrowWorkerResponse], error)
	// Extend the ttl a worker key. This is useful if your worker keys a store in a database that support ttl
	// If the organization has exceeded his resource consumption (other than the pool, ex: bytes, requests, blocks...),
	//
	//	an error will be returned with code ResourceExhausted
	KeepAlive(context.Context, *connect.Request[v1.KeepAliveRequest]) (*connect.Response[v1.KeepAliveResponse], error)
	// Returning a worker should increase the number of worker available for a organization/service pair
	ReturnWorker(context.Context, *connect.Request[v1.ReturnWorkerRequest]) (*connect.Response[v1.ReturnWorkerResponse], error)
}

// NewWorkerPoolHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWorkerPoolHandler(svc WorkerPoolHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	workerPoolWorkersStateHandler := connect.NewUnaryHandler(
		WorkerPoolWorkersStateProcedure,
		svc.WorkersState,
		connect.WithSchema(workerPoolWorkersStateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	workerPoolBorrowWorkerHandler := connect.NewUnaryHandler(
		WorkerPoolBorrowWorkerProcedure,
		svc.BorrowWorker,
		connect.WithSchema(workerPoolBorrowWorkerMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	workerPoolKeepAliveHandler := connect.NewUnaryHandler(
		WorkerPoolKeepAliveProcedure,
		svc.KeepAlive,
		connect.WithSchema(workerPoolKeepAliveMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	workerPoolReturnWorkerHandler := connect.NewUnaryHandler(
		WorkerPoolReturnWorkerProcedure,
		svc.ReturnWorker,
		connect.WithSchema(workerPoolReturnWorkerMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/sf.worker.v1.WorkerPool/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WorkerPoolWorkersStateProcedure:
			workerPoolWorkersStateHandler.ServeHTTP(w, r)
		case WorkerPoolBorrowWorkerProcedure:
			workerPoolBorrowWorkerHandler.ServeHTTP(w, r)
		case WorkerPoolKeepAliveProcedure:
			workerPoolKeepAliveHandler.ServeHTTP(w, r)
		case WorkerPoolReturnWorkerProcedure:
			workerPoolReturnWorkerHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWorkerPoolHandler returns CodeUnimplemented from all methods.
type UnimplementedWorkerPoolHandler struct{}

func (UnimplementedWorkerPoolHandler) WorkersState(context.Context, *connect.Request[v1.WorkersStateRequest]) (*connect.Response[v1.WorkersStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sf.worker.v1.WorkerPool.WorkersState is not implemented"))
}

func (UnimplementedWorkerPoolHandler) BorrowWorker(context.Context, *connect.Request[v1.BorrowWorkerRequest]) (*connect.Response[v1.BorrowWorkerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sf.worker.v1.WorkerPool.BorrowWorker is not implemented"))
}

func (UnimplementedWorkerPoolHandler) KeepAlive(context.Context, *connect.Request[v1.KeepAliveRequest]) (*connect.Response[v1.KeepAliveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sf.worker.v1.WorkerPool.KeepAlive is not implemented"))
}

func (UnimplementedWorkerPoolHandler) ReturnWorker(context.Context, *connect.Request[v1.ReturnWorkerRequest]) (*connect.Response[v1.ReturnWorkerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sf.worker.v1.WorkerPool.ReturnWorker is not implemented"))
}
