// Code generated by protoc-gen-go-grpc-mock. DO NOT EDIT.
// source: sf/worker/v1/pool.proto

package pbworker

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockWorkerPoolClient is a mock of WorkerPoolClient interface.
type MockWorkerPoolClient struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerPoolClientMockRecorder
}

// MockWorkerPoolClientMockRecorder is the mock recorder for MockWorkerPoolClient.
type MockWorkerPoolClientMockRecorder struct {
	mock *MockWorkerPoolClient
}

// NewMockWorkerPoolClient creates a new mock instance.
func NewMockWorkerPoolClient(ctrl *gomock.Controller) *MockWorkerPoolClient {
	mock := &MockWorkerPoolClient{ctrl: ctrl}
	mock.recorder = &MockWorkerPoolClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerPoolClient) EXPECT() *MockWorkerPoolClientMockRecorder {
	return m.recorder
}

// BorrowWorker mocks base method.
func (m *MockWorkerPoolClient) BorrowWorker(ctx context.Context, in *BorrowWorkerRequest, opts ...grpc.CallOption) (*BorrowWorkerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BorrowWorker", varargs...)
	ret0, _ := ret[0].(*BorrowWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BorrowWorker indicates an expected call of BorrowWorker.
func (mr *MockWorkerPoolClientMockRecorder) BorrowWorker(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BorrowWorker", reflect.TypeOf((*MockWorkerPoolClient)(nil).BorrowWorker), varargs...)
}

// KeepAlive mocks base method.
func (m *MockWorkerPoolClient) KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "KeepAlive", varargs...)
	ret0, _ := ret[0].(*KeepAliveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeepAlive indicates an expected call of KeepAlive.
func (mr *MockWorkerPoolClientMockRecorder) KeepAlive(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeepAlive", reflect.TypeOf((*MockWorkerPoolClient)(nil).KeepAlive), varargs...)
}

// ReturnWorker mocks base method.
func (m *MockWorkerPoolClient) ReturnWorker(ctx context.Context, in *ReturnWorkerRequest, opts ...grpc.CallOption) (*ReturnWorkerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReturnWorker", varargs...)
	ret0, _ := ret[0].(*ReturnWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReturnWorker indicates an expected call of ReturnWorker.
func (mr *MockWorkerPoolClientMockRecorder) ReturnWorker(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReturnWorker", reflect.TypeOf((*MockWorkerPoolClient)(nil).ReturnWorker), varargs...)
}

// WorkersState mocks base method.
func (m *MockWorkerPoolClient) WorkersState(ctx context.Context, in *WorkersStateRequest, opts ...grpc.CallOption) (*WorkersStateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WorkersState", varargs...)
	ret0, _ := ret[0].(*WorkersStateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkersState indicates an expected call of WorkersState.
func (mr *MockWorkerPoolClientMockRecorder) WorkersState(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkersState", reflect.TypeOf((*MockWorkerPoolClient)(nil).WorkersState), varargs...)
}

// MockWorkerPoolServer is a mock of WorkerPoolServer interface.
type MockWorkerPoolServer struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerPoolServerMockRecorder
}

// MockWorkerPoolServerMockRecorder is the mock recorder for MockWorkerPoolServer.
type MockWorkerPoolServerMockRecorder struct {
	mock *MockWorkerPoolServer
}

// NewMockWorkerPoolServer creates a new mock instance.
func NewMockWorkerPoolServer(ctrl *gomock.Controller) *MockWorkerPoolServer {
	mock := &MockWorkerPoolServer{ctrl: ctrl}
	mock.recorder = &MockWorkerPoolServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerPoolServer) EXPECT() *MockWorkerPoolServerMockRecorder {
	return m.recorder
}

// BorrowWorker mocks base method.
func (m *MockWorkerPoolServer) BorrowWorker(ctx context.Context, in *BorrowWorkerRequest) (*BorrowWorkerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BorrowWorker", ctx, in)
	ret0, _ := ret[0].(*BorrowWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BorrowWorker indicates an expected call of BorrowWorker.
func (mr *MockWorkerPoolServerMockRecorder) BorrowWorker(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BorrowWorker", reflect.TypeOf((*MockWorkerPoolServer)(nil).BorrowWorker), ctx, in)
}

// KeepAlive mocks base method.
func (m *MockWorkerPoolServer) KeepAlive(ctx context.Context, in *KeepAliveRequest) (*KeepAliveResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeepAlive", ctx, in)
	ret0, _ := ret[0].(*KeepAliveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeepAlive indicates an expected call of KeepAlive.
func (mr *MockWorkerPoolServerMockRecorder) KeepAlive(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeepAlive", reflect.TypeOf((*MockWorkerPoolServer)(nil).KeepAlive), ctx, in)
}

// ReturnWorker mocks base method.
func (m *MockWorkerPoolServer) ReturnWorker(ctx context.Context, in *ReturnWorkerRequest) (*ReturnWorkerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReturnWorker", ctx, in)
	ret0, _ := ret[0].(*ReturnWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReturnWorker indicates an expected call of ReturnWorker.
func (mr *MockWorkerPoolServerMockRecorder) ReturnWorker(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReturnWorker", reflect.TypeOf((*MockWorkerPoolServer)(nil).ReturnWorker), ctx, in)
}

// WorkersState mocks base method.
func (m *MockWorkerPoolServer) WorkersState(ctx context.Context, in *WorkersStateRequest) (*WorkersStateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkersState", ctx, in)
	ret0, _ := ret[0].(*WorkersStateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkersState indicates an expected call of WorkersState.
func (mr *MockWorkerPoolServerMockRecorder) WorkersState(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkersState", reflect.TypeOf((*MockWorkerPoolServer)(nil).WorkersState), ctx, in)
}
