// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: sf/worker/v1/pool.proto

package pbworker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WorkerPool_WorkersState_FullMethodName = "/sf.worker.v1.WorkerPool/WorkersState"
	WorkerPool_BorrowWorker_FullMethodName = "/sf.worker.v1.WorkerPool/BorrowWorker"
	WorkerPool_KeepAlive_FullMethodName    = "/sf.worker.v1.WorkerPool/KeepAlive"
	WorkerPool_ReturnWorker_FullMethodName = "/sf.worker.v1.WorkerPool/ReturnWorker"
)

// WorkerPoolClient is the client API for WorkerPool service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerPoolClient interface {
	WorkersState(ctx context.Context, in *WorkersStateRequest, opts ...grpc.CallOption) (*WorkersStateResponse, error)
	BorrowWorker(ctx context.Context, in *BorrowWorkerRequest, opts ...grpc.CallOption) (*BorrowWorkerResponse, error)
	KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error)
	ReturnWorker(ctx context.Context, in *ReturnWorkerRequest, opts ...grpc.CallOption) (*ReturnWorkerResponse, error)
}

type workerPoolClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerPoolClient(cc grpc.ClientConnInterface) WorkerPoolClient {
	return &workerPoolClient{cc}
}

func (c *workerPoolClient) WorkersState(ctx context.Context, in *WorkersStateRequest, opts ...grpc.CallOption) (*WorkersStateResponse, error) {
	out := new(WorkersStateResponse)
	err := c.cc.Invoke(ctx, WorkerPool_WorkersState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerPoolClient) BorrowWorker(ctx context.Context, in *BorrowWorkerRequest, opts ...grpc.CallOption) (*BorrowWorkerResponse, error) {
	out := new(BorrowWorkerResponse)
	err := c.cc.Invoke(ctx, WorkerPool_BorrowWorker_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerPoolClient) KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error) {
	out := new(KeepAliveResponse)
	err := c.cc.Invoke(ctx, WorkerPool_KeepAlive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerPoolClient) ReturnWorker(ctx context.Context, in *ReturnWorkerRequest, opts ...grpc.CallOption) (*ReturnWorkerResponse, error) {
	out := new(ReturnWorkerResponse)
	err := c.cc.Invoke(ctx, WorkerPool_ReturnWorker_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerPoolServer is the server API for WorkerPool service.
// All implementations must embed UnimplementedWorkerPoolServer
// for forward compatibility
type WorkerPoolServer interface {
	WorkersState(context.Context, *WorkersStateRequest) (*WorkersStateResponse, error)
	BorrowWorker(context.Context, *BorrowWorkerRequest) (*BorrowWorkerResponse, error)
	KeepAlive(context.Context, *KeepAliveRequest) (*KeepAliveResponse, error)
	ReturnWorker(context.Context, *ReturnWorkerRequest) (*ReturnWorkerResponse, error)
	mustEmbedUnimplementedWorkerPoolServer()
}

// UnimplementedWorkerPoolServer must be embedded to have forward compatible implementations.
type UnimplementedWorkerPoolServer struct {
}

func (UnimplementedWorkerPoolServer) WorkersState(context.Context, *WorkersStateRequest) (*WorkersStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkersState not implemented")
}
func (UnimplementedWorkerPoolServer) BorrowWorker(context.Context, *BorrowWorkerRequest) (*BorrowWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BorrowWorker not implemented")
}
func (UnimplementedWorkerPoolServer) KeepAlive(context.Context, *KeepAliveRequest) (*KeepAliveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeepAlive not implemented")
}
func (UnimplementedWorkerPoolServer) ReturnWorker(context.Context, *ReturnWorkerRequest) (*ReturnWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnWorker not implemented")
}
func (UnimplementedWorkerPoolServer) mustEmbedUnimplementedWorkerPoolServer() {}

// UnsafeWorkerPoolServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerPoolServer will
// result in compilation errors.
type UnsafeWorkerPoolServer interface {
	mustEmbedUnimplementedWorkerPoolServer()
}

func RegisterWorkerPoolServer(s grpc.ServiceRegistrar, srv WorkerPoolServer) {
	s.RegisterService(&WorkerPool_ServiceDesc, srv)
}

func _WorkerPool_WorkersState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkersStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerPoolServer).WorkersState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerPool_WorkersState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerPoolServer).WorkersState(ctx, req.(*WorkersStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerPool_BorrowWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BorrowWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerPoolServer).BorrowWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerPool_BorrowWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerPoolServer).BorrowWorker(ctx, req.(*BorrowWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerPool_KeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerPoolServer).KeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerPool_KeepAlive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerPoolServer).KeepAlive(ctx, req.(*KeepAliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerPool_ReturnWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerPoolServer).ReturnWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerPool_ReturnWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerPoolServer).ReturnWorker(ctx, req.(*ReturnWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerPool_ServiceDesc is the grpc.ServiceDesc for WorkerPool service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerPool_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sf.worker.v1.WorkerPool",
	HandlerType: (*WorkerPoolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WorkersState",
			Handler:    _WorkerPool_WorkersState_Handler,
		},
		{
			MethodName: "BorrowWorker",
			Handler:    _WorkerPool_BorrowWorker_Handler,
		},
		{
			MethodName: "KeepAlive",
			Handler:    _WorkerPool_KeepAlive_Handler,
		},
		{
			MethodName: "ReturnWorker",
			Handler:    _WorkerPool_ReturnWorker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sf/worker/v1/pool.proto",
}
