// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: sf/worker/v1/pool.proto

package pbworker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BorrowWorkerResponse_BorrowStatus int32

const (
	BorrowWorkerResponse_unset              BorrowWorkerResponse_BorrowStatus = 0
	BorrowWorkerResponse_borrowed           BorrowWorkerResponse_BorrowStatus = 1
	BorrowWorkerResponse_resource_exhausted BorrowWorkerResponse_BorrowStatus = 2
)

// Enum value maps for BorrowWorkerResponse_BorrowStatus.
var (
	BorrowWorkerResponse_BorrowStatus_name = map[int32]string{
		0: "unset",
		1: "borrowed",
		2: "resource_exhausted",
	}
	BorrowWorkerResponse_BorrowStatus_value = map[string]int32{
		"unset":              0,
		"borrowed":           1,
		"resource_exhausted": 2,
	}
)

func (x BorrowWorkerResponse_BorrowStatus) Enum() *BorrowWorkerResponse_BorrowStatus {
	p := new(BorrowWorkerResponse_BorrowStatus)
	*p = x
	return p
}

func (x BorrowWorkerResponse_BorrowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BorrowWorkerResponse_BorrowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sf_worker_v1_pool_proto_enumTypes[0].Descriptor()
}

func (BorrowWorkerResponse_BorrowStatus) Type() protoreflect.EnumType {
	return &file_sf_worker_v1_pool_proto_enumTypes[0]
}

func (x BorrowWorkerResponse_BorrowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BorrowWorkerResponse_BorrowStatus.Descriptor instead.
func (BorrowWorkerResponse_BorrowStatus) EnumDescriptor() ([]byte, []int) {
	return file_sf_worker_v1_pool_proto_rawDescGZIP(), []int{3, 0}
}

type KeepAliveResponse_Status int32

const (
	KeepAliveResponse_unset        KeepAliveResponse_Status = 0
	KeepAliveResponse_ttl_extended KeepAliveResponse_Status = 1
)

// Enum value maps for KeepAliveResponse_Status.
var (
	KeepAliveResponse_Status_name = map[int32]string{
		0: "unset",
		1: "ttl_extended",
	}
	KeepAliveResponse_Status_value = map[string]int32{
		"unset":        0,
		"ttl_extended": 1,
	}
)

func (x KeepAliveResponse_Status) Enum() *KeepAliveResponse_Status {
	p := new(KeepAliveResponse_Status)
	*p = x
	return p
}

func (x KeepAliveResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeepAliveResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_sf_worker_v1_pool_proto_enumTypes[1].Descriptor()
}

func (KeepAliveResponse_Status) Type() protoreflect.EnumType {
	return &file_sf_worker_v1_pool_proto_enumTypes[1]
}

func (x KeepAliveResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeepAliveResponse_Status.Descriptor instead.
func (KeepAliveResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_sf_worker_v1_pool_proto_rawDescGZIP(), []int{5, 0}
}

type WorkersStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MaxWorkers int64  `protobuf:"varint,2,opt,name=max_workers,json=maxWorkers,proto3" json:"max_workers,omitempty"`
}

func (x *WorkersStateRequest) Reset() {
	*x = WorkersStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_worker_v1_pool_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkersStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkersStateRequest) ProtoMessage() {}

func (x *WorkersStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_worker_v1_pool_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkersStateRequest.ProtoReflect.Descriptor instead.
func (*WorkersStateRequest) Descriptor() ([]byte, []int) {
	return file_sf_worker_v1_pool_proto_rawDescGZIP(), []int{0}
}

func (x *WorkersStateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WorkersStateRequest) GetMaxWorkers() int64 {
	if x != nil {
		return x.MaxWorkers
	}
	return 0
}

type WorkersStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerState *WorkersState `protobuf:"bytes,1,opt,name=worker_state,json=workerState,proto3" json:"worker_state,omitempty"`
}

func (x *WorkersStateResponse) Reset() {
	*x = WorkersStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_worker_v1_pool_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkersStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkersStateResponse) ProtoMessage() {}

func (x *WorkersStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_worker_v1_pool_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkersStateResponse.ProtoReflect.Descriptor instead.
func (*WorkersStateResponse) Descriptor() ([]byte, []int) {
	return file_sf_worker_v1_pool_proto_rawDescGZIP(), []int{1}
}

func (x *WorkersStateResponse) GetWorkerState() *WorkersState {
	if x != nil {
		return x.WorkerState
	}
	return nil
}

type BorrowWorkerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId              string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TraceId             string `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	MaxWorkerForTraceId int64  `protobuf:"varint,3,opt,name=max_worker_for_trace_id,json=maxWorkerForTraceId,proto3" json:"max_worker_for_trace_id,omitempty"`
}

func (x *BorrowWorkerRequest) Reset() {
	*x = BorrowWorkerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_worker_v1_pool_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BorrowWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowWorkerRequest) ProtoMessage() {}

func (x *BorrowWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_worker_v1_pool_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowWorkerRequest.ProtoReflect.Descriptor instead.
func (*BorrowWorkerRequest) Descriptor() ([]byte, []int) {
	return file_sf_worker_v1_pool_proto_rawDescGZIP(), []int{2}
}

func (x *BorrowWorkerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BorrowWorkerRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *BorrowWorkerRequest) GetMaxWorkerForTraceId() int64 {
	if x != nil {
		return x.MaxWorkerForTraceId
	}
	return 0
}

type BorrowWorkerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerKey string                            `protobuf:"bytes,1,opt,name=worker_key,json=workerKey,proto3" json:"worker_key,omitempty"`
	Status    BorrowWorkerResponse_BorrowStatus `protobuf:"varint,2,opt,name=status,proto3,enum=sf.worker.v1.BorrowWorkerResponse_BorrowStatus" json:"status,omitempty"`
}

func (x *BorrowWorkerResponse) Reset() {
	*x = BorrowWorkerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_worker_v1_pool_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BorrowWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowWorkerResponse) ProtoMessage() {}

func (x *BorrowWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_worker_v1_pool_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowWorkerResponse.ProtoReflect.Descriptor instead.
func (*BorrowWorkerResponse) Descriptor() ([]byte, []int) {
	return file_sf_worker_v1_pool_proto_rawDescGZIP(), []int{3}
}

func (x *BorrowWorkerResponse) GetWorkerKey() string {
	if x != nil {
		return x.WorkerKey
	}
	return ""
}

func (x *BorrowWorkerResponse) GetStatus() BorrowWorkerResponse_BorrowStatus {
	if x != nil {
		return x.Status
	}
	return BorrowWorkerResponse_unset
}

type KeepAliveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerKey string `protobuf:"bytes,1,opt,name=worker_key,json=workerKey,proto3" json:"worker_key,omitempty"`
}

func (x *KeepAliveRequest) Reset() {
	*x = KeepAliveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_worker_v1_pool_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeepAliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveRequest) ProtoMessage() {}

func (x *KeepAliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_worker_v1_pool_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveRequest.ProtoReflect.Descriptor instead.
func (*KeepAliveRequest) Descriptor() ([]byte, []int) {
	return file_sf_worker_v1_pool_proto_rawDescGZIP(), []int{4}
}

func (x *KeepAliveRequest) GetWorkerKey() string {
	if x != nil {
		return x.WorkerKey
	}
	return ""
}

type KeepAliveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status KeepAliveResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=sf.worker.v1.KeepAliveResponse_Status" json:"status,omitempty"`
}

func (x *KeepAliveResponse) Reset() {
	*x = KeepAliveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_worker_v1_pool_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeepAliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveResponse) ProtoMessage() {}

func (x *KeepAliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_worker_v1_pool_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveResponse.ProtoReflect.Descriptor instead.
func (*KeepAliveResponse) Descriptor() ([]byte, []int) {
	return file_sf_worker_v1_pool_proto_rawDescGZIP(), []int{5}
}

func (x *KeepAliveResponse) GetStatus() KeepAliveResponse_Status {
	if x != nil {
		return x.Status
	}
	return KeepAliveResponse_unset
}

type ReturnWorkerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerKey string `protobuf:"bytes,1,opt,name=worker_key,json=workerKey,proto3" json:"worker_key,omitempty"`
}

func (x *ReturnWorkerRequest) Reset() {
	*x = ReturnWorkerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_worker_v1_pool_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnWorkerRequest) ProtoMessage() {}

func (x *ReturnWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_worker_v1_pool_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnWorkerRequest.ProtoReflect.Descriptor instead.
func (*ReturnWorkerRequest) Descriptor() ([]byte, []int) {
	return file_sf_worker_v1_pool_proto_rawDescGZIP(), []int{6}
}

func (x *ReturnWorkerRequest) GetWorkerKey() string {
	if x != nil {
		return x.WorkerKey
	}
	return ""
}

type ReturnWorkerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReturnWorkerResponse) Reset() {
	*x = ReturnWorkerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_worker_v1_pool_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnWorkerResponse) ProtoMessage() {}

func (x *ReturnWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_worker_v1_pool_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnWorkerResponse.ProtoReflect.Descriptor instead.
func (*ReturnWorkerResponse) Descriptor() ([]byte, []int) {
	return file_sf_worker_v1_pool_proto_rawDescGZIP(), []int{7}
}

type WorkersState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvailableWorkers      int64            `protobuf:"varint,1,opt,name=available_workers,json=availableWorkers,proto3" json:"available_workers,omitempty"`
	BorrowedWorkers       int64            `protobuf:"varint,2,opt,name=borrowed_workers,json=borrowedWorkers,proto3" json:"borrowed_workers,omitempty"`
	MaxWorkers            int64            `protobuf:"varint,3,opt,name=max_workers,json=maxWorkers,proto3" json:"max_workers,omitempty"`
	ActiveRequest         int64            `protobuf:"varint,10,opt,name=active_request,json=activeRequest,proto3" json:"active_request,omitempty"`
	WorkerCountPerTraceId map[string]int64 `protobuf:"bytes,20,rep,name=worker_count_per_trace_id,json=workerCountPerTraceId,proto3" json:"worker_count_per_trace_id,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *WorkersState) Reset() {
	*x = WorkersState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_worker_v1_pool_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkersState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkersState) ProtoMessage() {}

func (x *WorkersState) ProtoReflect() protoreflect.Message {
	mi := &file_sf_worker_v1_pool_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkersState.ProtoReflect.Descriptor instead.
func (*WorkersState) Descriptor() ([]byte, []int) {
	return file_sf_worker_v1_pool_proto_rawDescGZIP(), []int{8}
}

func (x *WorkersState) GetAvailableWorkers() int64 {
	if x != nil {
		return x.AvailableWorkers
	}
	return 0
}

func (x *WorkersState) GetBorrowedWorkers() int64 {
	if x != nil {
		return x.BorrowedWorkers
	}
	return 0
}

func (x *WorkersState) GetMaxWorkers() int64 {
	if x != nil {
		return x.MaxWorkers
	}
	return 0
}

func (x *WorkersState) GetActiveRequest() int64 {
	if x != nil {
		return x.ActiveRequest
	}
	return 0
}

func (x *WorkersState) GetWorkerCountPerTraceId() map[string]int64 {
	if x != nil {
		return x.WorkerCountPerTraceId
	}
	return nil
}

var File_sf_worker_v1_pool_proto protoreflect.FileDescriptor

var file_sf_worker_v1_pool_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x66, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x70,
	0x6f, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x66, 0x2e, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x13, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x5f, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x57,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x22, 0x55, 0x0a, 0x14, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d,
	0x0a, 0x0c, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x7f, 0x0a,
	0x13, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x17, 0x6d, 0x61, 0x78, 0x5f,
	0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x6d, 0x61, 0x78, 0x57, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x22, 0xbf,
	0x01, 0x0a, 0x14, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x47, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2f, 0x2e, 0x73, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x57, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x3f, 0x0a, 0x0c, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x09, 0x0a, 0x05, 0x75, 0x6e, 0x73, 0x65, 0x74, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x62, 0x6f,
	0x72, 0x72, 0x6f, 0x77, 0x65, 0x64, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x65, 0x78, 0x68, 0x61, 0x75, 0x73, 0x74, 0x65, 0x64, 0x10, 0x02,
	0x22, 0x31, 0x0a, 0x10, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x4b, 0x65, 0x79, 0x22, 0x7a, 0x0a, 0x11, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x73, 0x66, 0x2e, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x25, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x75, 0x6e, 0x73, 0x65, 0x74, 0x10, 0x00, 0x12, 0x10, 0x0a,
	0x0c, 0x74, 0x74, 0x6c, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x10, 0x01, 0x22,
	0x34, 0x0a, 0x13, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x4b, 0x65, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x57,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xe9, 0x02,
	0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2b,
	0x0a, 0x11, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x77, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x62,
	0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x64, 0x57,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x5f, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x61, 0x78,
	0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x6f,
	0x0a, 0x19, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x70,
	0x65, 0x72, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x14, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x35, 0x2e, 0x73, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x57, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x65, 0x72, 0x54, 0x72, 0x61, 0x63,
	0x65, 0x49, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x15, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x65, 0x72, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x1a,
	0x48, 0x0a, 0x1a, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x65,
	0x72, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0xdf, 0x02, 0x0a, 0x0a, 0x57, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x55, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x73, 0x66, 0x2e, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x66,
	0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x55, 0x0a, 0x0c, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12,
	0x21, 0x2e, 0x73, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42,
	0x6f, 0x72, 0x72, 0x6f, 0x77, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x09, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c,
	0x69, 0x76, 0x65, 0x12, 0x1e, 0x2e, 0x73, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x0c, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x57, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x73, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x66, 0x2e, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x57, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x48, 0x5a, 0x46, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x69, 0x6e, 0x67, 0x66, 0x61, 0x73, 0x74, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2d, 0x70,
	0x6f, 0x6f, 0x6c, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x2f,
	0x73, 0x66, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x62, 0x77,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sf_worker_v1_pool_proto_rawDescOnce sync.Once
	file_sf_worker_v1_pool_proto_rawDescData = file_sf_worker_v1_pool_proto_rawDesc
)

func file_sf_worker_v1_pool_proto_rawDescGZIP() []byte {
	file_sf_worker_v1_pool_proto_rawDescOnce.Do(func() {
		file_sf_worker_v1_pool_proto_rawDescData = protoimpl.X.CompressGZIP(file_sf_worker_v1_pool_proto_rawDescData)
	})
	return file_sf_worker_v1_pool_proto_rawDescData
}

var file_sf_worker_v1_pool_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sf_worker_v1_pool_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_sf_worker_v1_pool_proto_goTypes = []interface{}{
	(BorrowWorkerResponse_BorrowStatus)(0), // 0: sf.worker.v1.BorrowWorkerResponse.BorrowStatus
	(KeepAliveResponse_Status)(0),          // 1: sf.worker.v1.KeepAliveResponse.Status
	(*WorkersStateRequest)(nil),            // 2: sf.worker.v1.WorkersStateRequest
	(*WorkersStateResponse)(nil),           // 3: sf.worker.v1.WorkersStateResponse
	(*BorrowWorkerRequest)(nil),            // 4: sf.worker.v1.BorrowWorkerRequest
	(*BorrowWorkerResponse)(nil),           // 5: sf.worker.v1.BorrowWorkerResponse
	(*KeepAliveRequest)(nil),               // 6: sf.worker.v1.KeepAliveRequest
	(*KeepAliveResponse)(nil),              // 7: sf.worker.v1.KeepAliveResponse
	(*ReturnWorkerRequest)(nil),            // 8: sf.worker.v1.ReturnWorkerRequest
	(*ReturnWorkerResponse)(nil),           // 9: sf.worker.v1.ReturnWorkerResponse
	(*WorkersState)(nil),                   // 10: sf.worker.v1.WorkersState
	nil,                                    // 11: sf.worker.v1.WorkersState.WorkerCountPerTraceIdEntry
}
var file_sf_worker_v1_pool_proto_depIdxs = []int32{
	10, // 0: sf.worker.v1.WorkersStateResponse.worker_state:type_name -> sf.worker.v1.WorkersState
	0,  // 1: sf.worker.v1.BorrowWorkerResponse.status:type_name -> sf.worker.v1.BorrowWorkerResponse.BorrowStatus
	1,  // 2: sf.worker.v1.KeepAliveResponse.status:type_name -> sf.worker.v1.KeepAliveResponse.Status
	11, // 3: sf.worker.v1.WorkersState.worker_count_per_trace_id:type_name -> sf.worker.v1.WorkersState.WorkerCountPerTraceIdEntry
	2,  // 4: sf.worker.v1.WorkerPool.WorkersState:input_type -> sf.worker.v1.WorkersStateRequest
	4,  // 5: sf.worker.v1.WorkerPool.BorrowWorker:input_type -> sf.worker.v1.BorrowWorkerRequest
	6,  // 6: sf.worker.v1.WorkerPool.KeepAlive:input_type -> sf.worker.v1.KeepAliveRequest
	8,  // 7: sf.worker.v1.WorkerPool.ReturnWorker:input_type -> sf.worker.v1.ReturnWorkerRequest
	3,  // 8: sf.worker.v1.WorkerPool.WorkersState:output_type -> sf.worker.v1.WorkersStateResponse
	5,  // 9: sf.worker.v1.WorkerPool.BorrowWorker:output_type -> sf.worker.v1.BorrowWorkerResponse
	7,  // 10: sf.worker.v1.WorkerPool.KeepAlive:output_type -> sf.worker.v1.KeepAliveResponse
	9,  // 11: sf.worker.v1.WorkerPool.ReturnWorker:output_type -> sf.worker.v1.ReturnWorkerResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_sf_worker_v1_pool_proto_init() }
func file_sf_worker_v1_pool_proto_init() {
	if File_sf_worker_v1_pool_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sf_worker_v1_pool_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkersStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sf_worker_v1_pool_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkersStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sf_worker_v1_pool_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BorrowWorkerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sf_worker_v1_pool_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BorrowWorkerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sf_worker_v1_pool_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeepAliveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sf_worker_v1_pool_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeepAliveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sf_worker_v1_pool_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnWorkerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sf_worker_v1_pool_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnWorkerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sf_worker_v1_pool_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkersState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sf_worker_v1_pool_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sf_worker_v1_pool_proto_goTypes,
		DependencyIndexes: file_sf_worker_v1_pool_proto_depIdxs,
		EnumInfos:         file_sf_worker_v1_pool_proto_enumTypes,
		MessageInfos:      file_sf_worker_v1_pool_proto_msgTypes,
	}.Build()
	File_sf_worker_v1_pool_proto = out.File
	file_sf_worker_v1_pool_proto_rawDesc = nil
	file_sf_worker_v1_pool_proto_goTypes = nil
	file_sf_worker_v1_pool_proto_depIdxs = nil
}
